version: "3.5"
services:
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/symfony/repo/branch/backend
      - /var/www/symfony/repo/branch/backend/vendor
      - /var/www/symfony/repo/branch/backend/var
  api:
    build:
      context: ./docker-compose/nginx
      dockerfile: Dockerfile
    ports:
      - "8082:80"

    volumes:
      - ./backend:/var/www/symfony/repo/branch/backend